// practice_1/src/App.tsx
import React from 'react';
import { Diary } from './Diary';
import View from './components/View';
import Form from './components/Form';
import { useState } from 'react';

  function App() {

  const [isEdit, setIsEdit] = useState(false);
  const [diaries, setDiaries] = useState<Diary>({
    weather:"晴れ",
    manager:"山田",
    sleep_time:9,
    start:"10:00",
    end:"17:00",
    comment:"はじめまして。"
  });

  const editHandler = () => {
    setIsEdit(true);
  }
  const viewHandler = () => {
    setIsEdit(false);
  }


  return (
    <div className="App">
      <h2>2022年09月22日の日記</h2>
      {isEdit ?
        <div>
          <div><button onClick={viewHandler} className='btn btn-primary mb-2'>戻る</button></div>
          <Form diaries={diaries} setDiaries={setDiaries}  onStop={viewHandler} />

        </div>

        :

        <div>
          <div><button onClick={editHandler} className='btn btn-success mb-2'>編集する</button></div>
          <View diaries={diaries} />
        </div>
      }


    </div>
  );
}

export default App;

// vue-diary/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import DiaryForm from "./components/DiaryForm.vue";
import DiaryView from "./components/DiaryView.vue";
import type {Diary} from "./components/Diary";

const isEdit = ref(false);
const editHandler = (): void => {
  isEdit.value = true;
}
const viewHandler = (): void => {
  isEdit.value = false;
}
const diary: Diary = {
  weather: "雨",
  manager: "山田",
  sleepTime: 9,
  start: "10:00",
  end: "17:00",
  comment: "はじめまして。"
};

</script>


<template>
  <div class="App">
    <h2>2022年09月22日の日記</h2>
    <template v-if="isEdit == true">
      <div><button v-on:click="viewHandler" class='btn btn-primary mb-2'>戻る</button></div>
      <DiaryForm v-bind:diary="diary" v-on:onStop="viewHandler" />
    </template>
    <template v-else="isEdit == false">
        <div><button v-on:click="editHandler" class='btn btn-success mb-2'>編集する</button></div>
        <DiaryView v-bind:diary="diary" />
    </template>
  </div>
</template>

<style scoped>
header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>
